// Must match the keys of GST_STATE_CODES in backend/app/core/invoice_constants.py
// exactly -- these names are compared server-side (case-insensitively) against
// "Maharashtra" to decide CGST+SGST vs IGST on generated tax invoices, so a
// mismatched spelling here would silently produce the wrong tax split.
export const INDIAN_STATES = [
  "Jammu and Kashmir",
  "Himachal Pradesh",
  "Punjab",
  "Chandigarh",
  "Uttarakhand",
  "Haryana",
  "Delhi",
  "Rajasthan",
  "Uttar Pradesh",
  "Bihar",
  "Sikkim",
  "Arunachal Pradesh",
  "Nagaland",
  "Manipur",
  "Mizoram",
  "Tripura",
  "Meghalaya",
  "Assam",
  "West Bengal",
  "Jharkhand",
  "Odisha",
  "Chhattisgarh",
  "Madhya Pradesh",
  "Gujarat",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Maharashtra",
  "Karnataka",
  "Goa",
  "Lakshadweep",
  "Kerala",
  "Tamil Nadu",
  "Puducherry",
  "Andaman and Nicobar Islands",
  "Telangana",
  "Andhra Pradesh",
  "Ladakh",
];
