"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-12

Hand-crafted (not autogenerated) so that the following are correct:
  - CHECK constraints on every VARCHAR-backed enum column (native_enum=False).
    Autogenerate emits CREATE TYPE / ENUM, which we intentionally avoid.
  - server_default on JSONB columns uses ::jsonb cast (autogenerate omits the cast).
  - GIN index on call_transcripts.full_text (functional index; autogenerate skips these).
  - organizations.sip_trunk_id FK added via ALTER TABLE after both tables exist
    (circular FK: organizations → sip_trunks → organizations).
  - sentiment CHECK uses IS NULL OR … to allow NULL values.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ── 1. organizations ───────────────────────────────────────────────────────────
    # sip_trunk_id column is created here without a FK constraint. The FK is added
    # after sip_trunks exists (step 3) to break the circular dependency.
    op.create_table(
        "organizations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(100), nullable=False),
        sa.Column("phone", sa.String(20), nullable=False, server_default=""),
        sa.Column("sip_trunk_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("sip_caller_id", sa.String(20), nullable=False, server_default=""),
        sa.Column("plan_tier", sa.String(50), nullable=False, server_default="starter"),
        sa.Column("monthly_call_quota", sa.Integer(), nullable=False, server_default="1000"),
        sa.Column("calls_used_this_period", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "billing_period_start",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "billing_period_end",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now() + INTERVAL '30 days'"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_organizations_slug"),
    )
    op.create_index("ix_organizations_slug", "organizations", ["slug"], unique=True)
    op.create_index("ix_organizations_sip_trunk_id", "organizations", ["sip_trunk_id"])
    op.create_index("ix_organizations_deleted_at", "organizations", ["deleted_at"])

    # ── 2. sip_trunks ──────────────────────────────────────────────────────────────
    op.create_table(
        "sip_trunks",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("livekit_trunk_id", sa.String(100), nullable=False),
        sa.Column("sip_domain", sa.String(255), nullable=False),
        sa.Column("sip_username", sa.String(255), nullable=False),
        sa.Column("sip_password", sa.String(255), nullable=False),
        sa.Column("caller_id", sa.String(20), nullable=False),
        sa.Column("transport", sa.String(16), nullable=False, server_default="tcp"),
        sa.Column("is_default", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "transport IN ('tcp', 'udp', 'tls')",
            name="ck_sip_trunks_transport",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sip_trunks_org_id", "sip_trunks", ["org_id"])
    op.create_index("ix_sip_trunks_deleted_at", "sip_trunks", ["deleted_at"])

    # ── 3. Deferred FK: organizations.sip_trunk_id → sip_trunks ───────────────────
    # Both tables now exist; safe to add the FK that completes the circular reference.
    op.create_foreign_key(
        "fk_organizations_default_sip_trunk",
        "organizations",
        "sip_trunks",
        ["sip_trunk_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # ── 4. users ───────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column("role", sa.String(32), nullable=False, server_default="agent"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('admin', 'manager', 'agent')",
            name="ck_users_role",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_org_id", "users", ["org_id"])
    op.create_index("ix_users_deleted_at", "users", ["deleted_at"])

    # ── 5. agent_templates ─────────────────────────────────────────────────────────
    op.create_table(
        "agent_templates",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("language", sa.String(32), nullable=False, server_default="hinglish"),
        sa.Column("welcome_message", sa.Text(), nullable=False, server_default=""),
        sa.Column("system_prompt", sa.Text(), nullable=False, server_default=""),
        sa.Column(
            "voice_id",
            sa.String(100),
            nullable=False,
            server_default="9BWtsMINqrJLrRacOk9x",
        ),
        sa.Column(
            "voice_provider",
            sa.String(32),
            nullable=False,
            server_default="elevenlabs",
        ),
        sa.Column(
            "llm_model",
            sa.String(100),
            nullable=False,
            server_default="llama-3.1-8b-instant",
        ),
        sa.Column("llm_temperature", sa.Float(), nullable=False, server_default="0.7"),
        sa.Column(
            "max_call_duration_seconds",
            sa.Integer(),
            nullable=False,
            server_default="600",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "language IN ('hinglish', 'hindi', 'english', 'marathi')",
            name="ck_agent_templates_language",
        ),
        sa.CheckConstraint(
            "voice_provider IN ('elevenlabs', 'deepgram')",
            name="ck_agent_templates_voice_provider",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_templates_org_id", "agent_templates", ["org_id"])
    op.create_index(
        "ix_agent_templates_created_by_id", "agent_templates", ["created_by_id"]
    )
    op.create_index(
        "ix_agent_templates_deleted_at", "agent_templates", ["deleted_at"]
    )

    # ── 6. campaigns ───────────────────────────────────────────────────────────────
    op.create_table(
        "campaigns",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "goal", sa.String(32), nullable=False, server_default="lead_generation"
        ),
        sa.Column("agent_template_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sip_trunk_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.String(32), nullable=False, server_default="draft"),
        sa.Column("total_contacts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("completed_calls", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("interested_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "calling_window_start",
            sa.Time(),
            nullable=False,
            server_default="09:00:00",
        ),
        sa.Column(
            "calling_window_end",
            sa.Time(),
            nullable=False,
            server_default="19:00:00",
        ),
        sa.Column(
            "calling_days",
            postgresql.JSONB(),
            nullable=False,
            # Autogenerate emits this without the ::jsonb cast — Postgres rejects
            # a plain string literal as a default for a JSONB column.
            server_default=sa.text(
                """'["mon","tue","wed","thu","fri","sat"]'::jsonb"""
            ),
        ),
        sa.Column(
            "timezone", sa.String(50), nullable=False, server_default="Asia/Kolkata"
        ),
        sa.Column("calls_per_minute", sa.Integer(), nullable=False, server_default="5"),
        sa.Column("max_retries", sa.Integer(), nullable=False, server_default="2"),
        sa.Column(
            "retry_after_minutes", sa.Integer(), nullable=False, server_default="60"
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "goal IN ('lead_generation', 'follow_up', 'survey', 'announcement')",
            name="ck_campaigns_goal",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'scheduled', 'running', 'paused', 'completed', 'failed')",
            name="ck_campaigns_status",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["agent_template_id"], ["agent_templates.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["sip_trunk_id"], ["sip_trunks.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Named composite index used by dashboard query: org's campaigns by status
    op.create_index("ix_campaigns_org_status", "campaigns", ["org_id", "status"])
    op.create_index("ix_campaigns_org_id", "campaigns", ["org_id"])
    op.create_index("ix_campaigns_created_by_id", "campaigns", ["created_by_id"])
    op.create_index(
        "ix_campaigns_agent_template_id", "campaigns", ["agent_template_id"]
    )
    op.create_index("ix_campaigns_sip_trunk_id", "campaigns", ["sip_trunk_id"])
    op.create_index("ix_campaigns_status", "campaigns", ["status"])
    op.create_index("ix_campaigns_deleted_at", "campaigns", ["deleted_at"])

    # ── 7. campaign_contacts ───────────────────────────────────────────────────────
    # Hard-deleted by design (high volume). No deleted_at column.
    op.create_table(
        "campaign_contacts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("phone", sa.String(20), nullable=False),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("company", sa.String(255), nullable=True),
        sa.Column(
            "custom_fields",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("status", sa.String(32), nullable=False, server_default="pending"),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'dialing', 'completed', 'no_answer', 'failed', 'do_not_call')",
            name="ck_campaign_contacts_status",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # FOR UPDATE SKIP LOCKED dispatcher index
    op.create_index(
        "ix_campaign_contacts_campaign_status",
        "campaign_contacts",
        ["campaign_id", "status"],
    )
    # DNC pre-check index
    op.create_index(
        "ix_campaign_contacts_org_phone",
        "campaign_contacts",
        ["org_id", "phone"],
    )
    op.create_index(
        "ix_campaign_contacts_campaign_id", "campaign_contacts", ["campaign_id"]
    )
    op.create_index(
        "ix_campaign_contacts_status", "campaign_contacts", ["status"]
    )

    # ── 8. calls ───────────────────────────────────────────────────────────────────
    # Append-only; never hard or soft deleted. No deleted_at column.
    op.create_table(
        "calls",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("contact_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("livekit_room_name", sa.String(255), nullable=False),
        sa.Column("sip_call_id", sa.String(255), nullable=True),
        sa.Column("phone_number", sa.String(20), nullable=False),
        sa.Column("direction", sa.String(16), nullable=False, server_default="outbound"),
        sa.Column("status", sa.String(32), nullable=False, server_default="initiated"),
        sa.Column("outcome", sa.String(32), nullable=False, server_default="pending"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("cost_inr", sa.Numeric(10, 2), nullable=True),
        sa.Column("recording_url", sa.String(1024), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.String(16), nullable=True),
        sa.Column(
            "extracted_data",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "direction IN ('outbound', 'inbound')",
            name="ck_calls_direction",
        ),
        sa.CheckConstraint(
            "status IN ('initiated', 'ringing', 'connected', 'completed',"
            " 'no_answer', 'busy', 'failed', 'cancelled')",
            name="ck_calls_status",
        ),
        sa.CheckConstraint(
            "outcome IN ('interested', 'not_interested', 'callback_requested',"
            " 'wrong_number', 'do_not_call', 'voicemail', 'pending')",
            name="ck_calls_outcome",
        ),
        # IS NULL OR … allows NULL sentiment (not yet determined)
        sa.CheckConstraint(
            "sentiment IS NULL OR sentiment IN ('positive', 'neutral', 'negative')",
            name="ck_calls_sentiment",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["campaign_contacts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("livekit_room_name", name="uq_calls_livekit_room_name"),
    )
    # Analytics composite indexes (named in model __table_args__)
    op.create_index("ix_calls_org_started_at", "calls", ["org_id", "started_at"])
    op.create_index("ix_calls_campaign_outcome", "calls", ["campaign_id", "outcome"])
    op.create_index("ix_calls_org_id", "calls", ["org_id"])
    op.create_index("ix_calls_campaign_id", "calls", ["campaign_id"])
    op.create_index("ix_calls_contact_id", "calls", ["contact_id"])
    op.create_index(
        "ix_calls_livekit_room_name", "calls", ["livekit_room_name"], unique=True
    )
    op.create_index("ix_calls_phone_number", "calls", ["phone_number"])
    op.create_index("ix_calls_status", "calls", ["status"])
    op.create_index("ix_calls_outcome", "calls", ["outcome"])

    # ── 9. call_transcripts ────────────────────────────────────────────────────────
    # One-to-one with calls. Only created_at (no updated_at — transcripts are
    # written once and never modified after creation).
    op.create_table(
        "call_transcripts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("call_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "segments",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id", name="uq_call_transcripts_call_id"),
    )
    # Functional GIN index for full-text search — autogenerate cannot emit this.
    # to_tsvector uses 'english' stemming; swap language if Hindi support is needed later.
    op.execute(
        "CREATE INDEX ix_call_transcripts_full_text_gin "
        "ON call_transcripts "
        "USING GIN (to_tsvector('english', COALESCE(full_text, '')))"
    )

    # ── 10. call_events ────────────────────────────────────────────────────────────
    # Append-only audit log. Only created_at — rows are never modified after insert.
    op.create_table(
        "call_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("call_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(100), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_call_events_call_id", "call_events", ["call_id"])

    # ── 11. api_keys ───────────────────────────────────────────────────────────────
    op.create_table(
        "api_keys",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("key_hash", sa.String(64), nullable=False),
        sa.Column("key_prefix", sa.String(20), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash", name="uq_api_keys_key_hash"),
    )
    op.create_index("ix_api_keys_org_id", "api_keys", ["org_id"])

    # ── 12. do_not_call_entries ────────────────────────────────────────────────────
    op.create_table(
        "do_not_call_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("phone_number", sa.String(20), nullable=False),
        sa.Column("reason", sa.String(32), nullable=False),
        sa.Column("source_call_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("added_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "reason IN ('user_request', 'wrong_number', 'complaint',"
            " 'manual_block', 'spam_report')",
            name="ck_do_not_call_entries_reason",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_call_id"], ["calls.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["added_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.UniqueConstraint("org_id", "phone_number", name="uq_dnc_org_phone"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_do_not_call_entries_org_id", "do_not_call_entries", ["org_id"]
    )
    op.create_index(
        "ix_do_not_call_entries_phone_number",
        "do_not_call_entries",
        ["phone_number"],
    )
    op.create_index(
        "ix_do_not_call_entries_source_call_id",
        "do_not_call_entries",
        ["source_call_id"],
    )

    # ── 13. system_dnc_entries ─────────────────────────────────────────────────────
    # Global DNC — no org_id. Populated from TRAI NCPR feed (Phase 10 Celery task).
    op.create_table(
        "system_dnc_entries",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("phone_number", sa.String(20), nullable=False),
        sa.Column("source", sa.String(32), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "source IN ('trai_ncpr', 'manual_admin', 'global_complaint')",
            name="ck_system_dnc_entries_source",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number", name="uq_system_dnc_entries_phone_number"),
    )
    op.create_index(
        "ix_system_dnc_entries_phone_number",
        "system_dnc_entries",
        ["phone_number"],
        unique=True,
    )


def downgrade() -> None:
    # Drop in reverse creation order.
    # Remove the deferred FK first (organizations still references sip_trunks).
    op.drop_constraint(
        "fk_organizations_default_sip_trunk", "organizations", type_="foreignkey"
    )

    op.drop_table("system_dnc_entries")
    op.drop_table("do_not_call_entries")
    op.drop_table("api_keys")
    op.drop_table("call_events")
    op.drop_table("call_transcripts")
    op.drop_table("calls")
    op.drop_table("campaign_contacts")
    op.drop_table("campaigns")
    op.drop_table("agent_templates")
    op.drop_table("users")
    op.drop_table("sip_trunks")
    op.drop_table("organizations")
