"""encrypt sip trunk credentials at rest

Revision ID: 0016
Revises: 0015
Create Date: 2026-07-26

Hand-crafted (not autogenerated): the autogenerate compare requires the DB to
already be stamped at head, and the live DB was still at 0014 when this was
written. The DDL here is straightforward enough to write directly — see
app/models/sip.py for the corresponding model change.

Changes:
  - sip_trunks.sip_password: VARCHAR(255) -> TEXT. Fernet ciphertext is longer
    than a typical plaintext password and can exceed 255 chars. The DB column
    name is unchanged; only app/models/sip.py's Python attribute for it was
    renamed (sip_password_encrypted), with a `sip_password` property added for
    transparent encrypt-on-write / decrypt-on-read.
  - sip_trunks.vobiz_auth_id (nullable): the org's own Vobiz account identifier
    for the self-serve connect flow (app/api/sip_trunks.py POST /connect-vobiz).
    Not secret on its own — stored plaintext like sip_username.
  - sip_trunks.vobiz_auth_token_encrypted (nullable): the matching Vobiz API
    auth token, Fernet-encrypted like sip_password.

DATA MIGRATION NOTE: any pre-existing sip_trunks.sip_password values (there
should be few or none — see the model's prior "stored as plaintext" warning)
were plaintext, not Fernet tokens. SipTrunk.sip_password now decrypts on
read and would raise DecryptionError on a plaintext value, so this migration
backfills: for every row, try to decrypt the current sip_password; if that
fails (not a valid Fernet token = still plaintext), encrypt it in place. This
is idempotent — safe to re-run — since already-encrypted rows decrypt
successfully and are left untouched.

Requires FERNET_KEY to be set in the environment this migration runs in
(loaded via app.config.settings, same as every other secret in this codebase).
"""
import sqlalchemy as sa
from alembic import op

revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column(
        "sip_trunks", "sip_password",
        existing_type=sa.String(255),
        type_=sa.Text(),
    )
    op.add_column("sip_trunks", sa.Column("vobiz_auth_id", sa.String(100), nullable=True))
    op.add_column("sip_trunks", sa.Column("vobiz_auth_token_encrypted", sa.Text(), nullable=True))

    # ── Backfill: encrypt any pre-existing plaintext sip_password values ──────
    from app.core.crypto import DecryptionError, decrypt_value, encrypt_value

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, sip_password FROM sip_trunks")).fetchall()
    for row in rows:
        try:
            decrypt_value(row.sip_password)
            continue  # already a valid Fernet token — leave as-is (idempotent)
        except DecryptionError:
            pass
        conn.execute(
            sa.text("UPDATE sip_trunks SET sip_password = :enc WHERE id = :id"),
            {"enc": encrypt_value(row.sip_password), "id": row.id},
        )


def downgrade() -> None:
    # sip_password is left as TEXT — reverting to VARCHAR(255) risks truncating
    # ciphertext longer than 255 chars, which would corrupt those rows.
    op.drop_column("sip_trunks", "vobiz_auth_token_encrypted")
    op.drop_column("sip_trunks", "vobiz_auth_id")
