/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedIntegrationsRouteImport } from './routes/_authed.integrations'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedContactsRouteImport } from './routes/_authed.contacts'
import { Route as AuthedAnalyticsRouteImport } from './routes/_authed.analytics'
import { Route as AuthedAgentsRouteImport } from './routes/_authed.agents'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed.admin.users'
import { Route as AuthedCampaignsIndexRouteImport } from './routes/_authed.campaigns.index'
import { Route as AuthedCallsIndexRouteImport } from './routes/_authed.calls.index'
import { Route as AuthedCampaignsNewRouteImport } from './routes/_authed.campaigns.new'
import { Route as AuthedCampaignsIdRouteImport } from './routes/_authed.campaigns.$id'
import { Route as AuthedCallsIdRouteImport } from './routes/_authed.calls.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIntegrationsRoute = AuthedIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContactsRoute = AuthedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsRoute = AuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsRoute = AuthedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsIndexRoute = AuthedCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCallsIndexRoute = AuthedCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsNewRoute = AuthedCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsIdRoute = AuthedCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCallsIdRoute = AuthedCallsIdRouteImport.update({
  id: '/calls/$id',
  path: '/calls/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agents': typeof AuthedAgentsRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/contacts': typeof AuthedContactsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/integrations': typeof AuthedIntegrationsRoute
  '/settings': typeof AuthedSettingsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/calls/$id': typeof AuthedCallsIdRoute
  '/campaigns/$id': typeof AuthedCampaignsIdRoute
  '/campaigns/new': typeof AuthedCampaignsNewRoute
  '/calls/': typeof AuthedCallsIndexRoute
  '/campaigns/': typeof AuthedCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agents': typeof AuthedAgentsRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/contacts': typeof AuthedContactsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/integrations': typeof AuthedIntegrationsRoute
  '/settings': typeof AuthedSettingsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/calls/$id': typeof AuthedCallsIdRoute
  '/campaigns/$id': typeof AuthedCampaignsIdRoute
  '/campaigns/new': typeof AuthedCampaignsNewRoute
  '/calls': typeof AuthedCallsIndexRoute
  '/campaigns': typeof AuthedCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/agents': typeof AuthedAgentsRoute
  '/_authed/analytics': typeof AuthedAnalyticsRoute
  '/_authed/contacts': typeof AuthedContactsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/integrations': typeof AuthedIntegrationsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/calls/$id': typeof AuthedCallsIdRoute
  '/_authed/campaigns/$id': typeof AuthedCampaignsIdRoute
  '/_authed/campaigns/new': typeof AuthedCampaignsNewRoute
  '/_authed/calls/': typeof AuthedCallsIndexRoute
  '/_authed/campaigns/': typeof AuthedCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/agents'
    | '/analytics'
    | '/contacts'
    | '/dashboard'
    | '/integrations'
    | '/settings'
    | '/admin/users'
    | '/calls/$id'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/calls/'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/agents'
    | '/analytics'
    | '/contacts'
    | '/dashboard'
    | '/integrations'
    | '/settings'
    | '/admin/users'
    | '/calls/$id'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/calls'
    | '/campaigns'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/agents'
    | '/_authed/analytics'
    | '/_authed/contacts'
    | '/_authed/dashboard'
    | '/_authed/integrations'
    | '/_authed/settings'
    | '/_authed/admin/users'
    | '/_authed/calls/$id'
    | '/_authed/campaigns/$id'
    | '/_authed/campaigns/new'
    | '/_authed/calls/'
    | '/_authed/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/integrations': {
      id: '/_authed/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthedIntegrationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contacts': {
      id: '/_authed/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthedContactsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics': {
      id: '/_authed/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedAnalyticsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents': {
      id: '/_authed/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthedAgentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campaigns/': {
      id: '/_authed/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthedCampaignsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calls/': {
      id: '/_authed/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof AuthedCallsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campaigns/new': {
      id: '/_authed/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthedCampaignsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campaigns/$id': {
      id: '/_authed/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthedCampaignsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calls/$id': {
      id: '/_authed/calls/$id'
      path: '/calls/$id'
      fullPath: '/calls/$id'
      preLoaderRoute: typeof AuthedCallsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAgentsRoute: typeof AuthedAgentsRoute
  AuthedAnalyticsRoute: typeof AuthedAnalyticsRoute
  AuthedContactsRoute: typeof AuthedContactsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedIntegrationsRoute: typeof AuthedIntegrationsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedCallsIdRoute: typeof AuthedCallsIdRoute
  AuthedCampaignsIdRoute: typeof AuthedCampaignsIdRoute
  AuthedCampaignsNewRoute: typeof AuthedCampaignsNewRoute
  AuthedCallsIndexRoute: typeof AuthedCallsIndexRoute
  AuthedCampaignsIndexRoute: typeof AuthedCampaignsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAgentsRoute: AuthedAgentsRoute,
  AuthedAnalyticsRoute: AuthedAnalyticsRoute,
  AuthedContactsRoute: AuthedContactsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedIntegrationsRoute: AuthedIntegrationsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedCallsIdRoute: AuthedCallsIdRoute,
  AuthedCampaignsIdRoute: AuthedCampaignsIdRoute,
  AuthedCampaignsNewRoute: AuthedCampaignsNewRoute,
  AuthedCallsIndexRoute: AuthedCallsIndexRoute,
  AuthedCampaignsIndexRoute: AuthedCampaignsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
